### ISSUE TITLE
Transform lenses to FHIR format

### ISSUE THREAD

**Issue by gmej** [Gravitate-Health/mvp-issues#32]
More information in issue #22 .

Current lenses must be transformed to FHIR format, and store them in FHIR server. Lenses require:
1. FSH file (metadata). Maybe there is a better format? I suggest stick to fsh as iti sknown and already used in GH.
2. JS file with the lens code
3. ci/cd pipeline to build the lens: JS code is base64 enconded in the FHIR lens at field ["content"]["data"]
4. Provenance

**Comment by aalonsolopez** [comment]
Should we build a Lens Bundler to pass from JS to FHIR?
