### ISSUE TITLE
[BUG] Correcting summary lens

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/mvp-issues#40]
1. correct title and use language for it
2. try to add html formatting to endpoint
3. apply logic similar to the others lenses of epi and ips added in the body

EDIT:

4. Performance

**Comment by joofio** [comment]
@aalonsolopez corrected the first one on my repo (upstream), can you look at the second and i will take a look at the third

**Comment by aalonsolopez** [comment]
A question:
Adding HTML formatting you mean in the response? For example:
```html
<div>{{summary}}</div>
```

**Comment by joofio** [comment]
no, what I meant with the HTML is formatting the output in terms of styling.
how it currently looks:
![image](https://github.com/Gravitate-Health/mvp-issues/assets/14195408/45b2636c-8489-4893-96ea-5bdcdf120f34)

see the bullets?

**Comment by aalonsolopez** [comment]
Ah! Of course, I can substitute the markdown bullets to an HTML unordered list

**Comment by joofio** [comment]
we hope to be more generic. but that would be a good first step.
we could also tweak with the prompt.

i suggest first taking on the errors and then this.

**Comment by aalonsolopez** [comment]
Perfect

**Comment by aalonsolopez** [comment]
A question. When the Lens fails because the model requested is not found, what is the expected output? Returning an error? Or picking another model "by default" to always have a useful response?

**Comment by joofio** [comment]
Error
A unknown model should not happen in production

**Comment by aalonsolopez** [comment]
Summary Lens is working rn

**Comment by joofio** [comment]
Added performance now.

**Comment by aalonsolopez** [comment]
Today I will start looking how can we cache requests

**Comment by aalonsolopez** [comment]
Temperature set to 0, Seed set to 1234. For my recent tests, the answers appear to be deterministic (or almost all, if the response varies may be for some changes in the prompt). @joofio give it a try.

**Comment by joofio** [comment]
it is in dev i assume right?

**Comment by joofio** [comment]
currently not working in dev.

**Comment by aalonsolopez** [comment]
at least rn it is working

**Comment by joofio** [comment]
bugs reported done. other issue and improvements in other issues
